global using System;
global using System.Diagnostics;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using System.Collections.Generic;
global using System.Windows;
global using System.Windows.Controls.Primitives;
global using System.Windows.Controls;
global using System.Windows.Data;
global using System.Windows.Documents;
global using System.Windows.Input;
global using System.Windows.Media;
global using System.Windows.Media.Imaging;
global using System.Windows.Navigation;
global using System.Windows.Shapes;
global using System.Globalization;
global using System.ComponentModel;
global using System.Runtime.CompilerServices;
global using System.Collections.ObjectModel;
global using Microsoft.Extensions.DependencyInjection;
global using MaterialDesignThemes.Wpf;

global using ArduinoInterface.UI.Core;
global using ArduinoInterface.UI.View;
global using ArduinoInterface.UI.Model;
global using ArduinoInterface.UI.ViewModel;
global using ArduinoInterface.UI.Converters;

